spring:
  application:
    name: production-grade-url-shortener
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: validate