spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:shortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO
    production_grade_url_shortener: DEBUG

