CREATE TABLE api_keys
(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    api_hash TEXT UNIQUE NOT NULL,
    user_id TEXT NOT NULL,
    is_active_api BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE NULL
);